baseURL = "https://example.com/"
languageCode = "en-us"
title = "Sumerset Apartments Orlando, FL"
theme = "tricky-triangles"
publishDir = "docs"

[params]
  image = "images/Sumerset.jpg"
  description = "Welcome to Sumerset Apartments, space aparatments, affordably priced, conveniently located"
[params.property]
  name = "Sumerset Apartments"
  phone = "407.645.0787"
  email = "sumersetapts@gmail.com"
[params.property.address]
  line1 = "1051 Lee Road"
  line2 = "Orlando, Florida 32810"
